//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsingReflection.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReflectionsEntities : DbContext
    {
        public ReflectionsEntities()
            : base("name=ReflectionsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmployDetail> EmployDetails { get; set; }
        public virtual DbSet<URL> URLs { get; set; }
        public virtual DbSet<Userss> Usersses { get; set; }
        public virtual DbSet<URLMappingToRole> URLMappingToRoles { get; set; }
    }
}
